{{- with .Values.postgres }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
type: Opaque
data:
{{- range $key, $value := .env }}
  {{- $key | nindent 2 }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
